"use client";
import { useDeferredValue, useState, type FormEvent } from "react";
import Link from "next/link";
import { Plus, Search, ArrowUpRight, Send, RefreshCw, CheckCircle2 } from "lucide-react";
import type { Actor } from "@/server/security";
import type { Analytics } from "@/server/analytics";
import type { Options, PageData, TraineeRow, FollowupRow, Verification } from "@/lib/types";
import { api, useResource } from "@/lib/client";
import { date, money } from "@/lib/utils";
import { Button } from "./ui/button";
import { Badge, Empty, ErrorState, Loading, Modal, PageHeader, Pagination, Panel, Status } from "./ui/common";
import { ComparisonTable } from "./analytics-views";

export function Directory() {
  const [search, setSearch] = useState(""); const deferredSearch = useDeferredValue(search); const [page, setPage] = useState(1); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const resource = useResource<PageData<TraineeRow>>(`trainees?${new URLSearchParams({ search: deferredSearch, page: String(page) })}`); const options = useResource<Options>("options");
  async function enroll(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setBusy(true); setError(""); try { await api("trainees", values); setOpen(false); resource.refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Persistent identity" title="Trainee directory" description="Longitudinal records within your authorised provider scope"><Button onClick={() => setOpen(true)}><Plus size={15} />Enroll trainee</Button></PageHeader><div className="filter-bar"><div className="search-field"><Search size={15} /><input aria-label="Search name or SkillID" placeholder="Search name or SkillID" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /></div></div><Panel title="Trainees" subtitle={resource.data ? `${resource.data.total} records in your scope` : "Loading records"}>{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} /> : resource.data && <><div className="table-scroll"><table><thead><tr><th>Trainee / SkillID</th><th>District</th><th>Programme</th><th>Certification</th><th>Current outcome</th><th>Verification</th></tr></thead><tbody>{resource.data.items.map(trainee => <tr key={trainee.id}><td><Link className="table-link" href={`/trainees/${trainee.id}`}><strong>{trainee.name}</strong><small>{trainee.skillId}</small></Link></td><td>{trainee.district.name}</td><td>{trainee.enrollments[0]?.program.name}<small>{trainee.enrollments[0]?.cohort}</small></td><td><Status value={trainee.enrollments[0]?.certification ? "CERTIFIED" : "IN_TRAINING"} /></td><td><Status value={trainee.employment[0]?.status ?? "NOT_REPORTED"} /></td><td><Status value={trainee.employment[0]?.verification?.status ?? "NOT_REQUESTED"} /></td></tr>)}</tbody></table>{!resource.data.total && <Empty title="No matching trainees" />}</div><Pagination {...resource.data} onChange={setPage} /></>}</Panel><Modal open={open} onOpenChange={setOpen} title="Enroll a trainee" description="A permanent SkillID is allocated. Consent is not granted on the trainee's behalf.">{error && <ErrorState message={error} />}<form className="form-stack" onSubmit={enroll}><label>Full name<input name="name" minLength={2} maxLength={100} required /></label><div className="form-grid"><label>District<select name="districtId" required>{options.data?.districts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Gender<select name="gender"><option>Woman</option><option>Man</option><option>Other</option><option>Prefer not to say</option></select></label></div><label>Programme<select name="programId" required>{options.data?.programs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Cohort<input name="cohort" defaultValue="2026-27" required /></label><Button disabled={busy || !options.data}>{busy ? "Enrolling..." : "Enroll trainee"}</Button></form></Modal></>;
}
export function Programs({ user }: { user: Actor }) {
  const resource = useResource<Analytics>("analytics"); const options = useResource<Options>("options"); const [tab, setTab] = useState("programs"); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setError(""); try { await api("programs", { name: values.get("name"), sector: values.get("sector"), providerId: values.get("providerId"), duration: Number(values.get("duration")), modules: String(values.get("modules")).split(",").map(value => value.trim()).filter(Boolean) }); setOpen(false); options.refresh(); resource.refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <><PageHeader eyebrow="Training to outcomes" title="Programmes & providers" description="Certification is the beginning, not the final measure.">{user.role !== "OFFICER" && <Button onClick={() => setOpen(true)}><Plus size={15} />Add programme</Button>}</PageHeader><div className="tabs"><button className={tab === "programs" ? "active" : ""} onClick={() => setTab("programs")}>Programme outcomes</button><button className={tab === "providers" ? "active" : ""} onClick={() => setTab("providers")}>Provider comparison</button><button className={tab === "catalog" ? "active" : ""} onClick={() => setTab("catalog")}>Training catalogue</button></div>{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} /> : resource.data && <Panel title={tab === "providers" ? "Provider performance" : tab === "catalog" ? "Training catalogue" : "Programme performance"} subtitle="Synthetic cohorts. Outcomes are descriptive, not causal rankings.">{tab !== "catalog" ? <ComparisonTable rows={tab === "providers" ? resource.data.providers : resource.data.courses} kind={tab === "providers" ? "Provider" : "Programme"} /> : <div className="table-scroll"><table><thead><tr><th>Programme</th><th>Provider</th><th>Duration</th><th>Modules</th></tr></thead><tbody>{options.data?.programs.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.sector}</small></td><td>{item.provider.name}</td><td>{item.duration} hours</td><td>{item.modules.join(", ")}</td></tr>)}</tbody></table></div>}</Panel>}<Modal open={open} onOpenChange={setOpen} title="Add training programme" description="Curriculum and provider ownership are recorded with the programme.">{error && <ErrorState message={error} />}<form className="form-stack" onSubmit={save}><label>Programme name<input name="name" required minLength={3} maxLength={100} /></label><label>Sector<input name="sector" required minLength={2} /></label><label>Provider<select name="providerId" required>{options.data?.providers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Duration in hours<input type="number" name="duration" min={1} max={2000} defaultValue={360} required /></label><label>Modules, separated by commas<textarea name="modules" required /></label><Button disabled={busy || !options.data}>{busy ? "Creating..." : "Create programme"}</Button></form></Modal></>;
}
export function Followups({ user }: { user: Actor }) {
  const [page, setPage] = useState(1); const resource = useResource<PageData<FollowupRow>>(`followups?page=${page}`); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function send(id: string) { setBusy(id); setError(""); try { await api(`trainees/${id}/followups`, {}); setMessage("Due follow-ups delivered to the trainee's in-app inbox."); resource.refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(""); } }
  return <><PageHeader eyebrow="30 / 90 / 180 / 365 days" title="Outcome follow-ups" description="Scheduled from certification; delivered only with current consent."><Button variant="outline" onClick={resource.refresh}><RefreshCw size={14} />Refresh</Button></PageHeader>{error && <ErrorState message={error} />}{message && <div className="success-message">{message}</div>}<Panel title="Upcoming and open checkpoints" subtitle="In-app delivery / no external SMS or WhatsApp messages">{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} /> : resource.data && <><div className="table-scroll"><table><thead><tr><th>Trainee</th><th>Checkpoint</th><th>Due date</th><th>Status</th><th>Action</th></tr></thead><tbody>{resource.data.items.map(item => <tr key={item.id}><td><Link href={user.role === "TRAINEE" ? "/my-profile" : `/trainees/${item.trainee.id}`}><strong>{item.trainee.name}</strong><small>{item.trainee.skillId}</small></Link></td><td>Day {item.checkpoint}</td><td>{date(item.dueAt)}</td><td><Status value={item.status} /></td><td>{user.role === "TRAINEE" ? <Button variant="outline" size="sm" asChild><Link href="/my-profile">Open profile<ArrowUpRight size={12} /></Link></Button> : <Button size="sm" variant="outline" disabled={Boolean(busy) || new Date(item.dueAt) > new Date()} onClick={() => send(item.trainee.id)}><Send size={12} />{busy === item.trainee.id ? "Sending..." : "Send due"}</Button>}</td></tr>)}</tbody></table>{!resource.data.total && <Empty title="No pending checkpoints" />}</div><Pagination {...resource.data} onChange={setPage} /></>}</Panel></>;
}
function VerificationCard({ item, refresh }: { item: Verification; refresh: () => void }) {
  const [checks, setChecks] = useState({ employmentOk: false, roleOk: false, salaryOk: false, startDateOk: false }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setError(""); try { await api(`verifications/${item.id}`, checks); refresh(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <article className="verification-card"><div className="verification-card-header"><div><h3>{item.employment.trainee.name}</h3><p className="fine-print">{item.employment.trainee.skillId}</p></div><Status value={item.status} /></div><dl className="detail-list"><div><dt>Role</dt><dd>{item.employment.role}</dd></div><div><dt>Employer</dt><dd>{item.employment.employer?.name}</dd></div><div><dt>Starting monthly salary</dt><dd>{money(item.employment.salaries[0]?.amount ?? 0)}</dd></div><div><dt>Start date</dt><dd>{date(item.employment.startDate)}</dd></div></dl>{error && <ErrorState message={error} />}{item.status === "PENDING" ? <><div className="verification-checks">{([{ key: "employmentOk", text: "Employment is confirmed" }, { key: "roleOk", text: "Job role matches our records" }, { key: "salaryOk", text: "Starting salary matches our records" }, { key: "startDateOk", text: "Start date matches our records" }] as const).map(check => <label className="checkbox-label" key={check.key}><input type="checkbox" checked={checks[check.key]} onChange={event => setChecks({ ...checks, [check.key]: event.target.checked })} />{check.text}</label>)}</div><p className="fine-print" style={{ marginBottom: 12 }}>Unchecked items are recorded as disputed. This confirmation covers the starting salary, not subsequent self-reported wage increases.</p><Button onClick={submit} disabled={busy}><CheckCircle2 size={14} />{busy ? "Submitting..." : Object.values(checks).every(Boolean) ? "Confirm employment" : "Submit disputed verification"}</Button></> : <Badge tone={item.status === "VERIFIED" ? "green" : "red"}>Verification score {item.score}/100</Badge>}</article>;
}
export function Employer() {
  const resource = useResource<Verification[]>("verifications"); const [tab, setTab] = useState("PENDING");
  return <><PageHeader eyebrow="Employer confirmation" title="Employment verification" description="Consent-authorised requests for your organisation only" /><div className="tabs">{["PENDING","VERIFIED","DISPUTED"].map(value => <button className={tab === value ? "active" : ""} onClick={() => setTab(value)} key={value}>{value.charAt(0) + value.slice(1).toLowerCase()} ({resource.data?.filter(item => item.status === value).length ?? 0})</button>)}</div>{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={resource.refresh} /> : <div className="verification-grid">{resource.data?.filter(item => item.status === tab).map(item => <VerificationCard item={item} key={item.id} refresh={resource.refresh} />)}{!resource.data?.some(item => item.status === tab) && <Empty title="No requests in this category" />}</div>}</>;
}
export function Audit() { const resource = useResource<{ id: string; actorId: string | null; action: string; entityId: string; createdAt: string }[]>("audit"); return <><PageHeader eyebrow="Accountability" title="Audit trail" description="Latest 100 server-recorded reads and mutations" /><Panel title="Recent activity">{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} /> : <div className="table-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Entity</th></tr></thead><tbody>{resource.data?.map(item => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString("en-IN")}</td><td className="audit-action">{item.action}</td><td>{item.actorId ?? "Unauthenticated"}</td><td>{item.entityId}</td></tr>)}</tbody></table></div>}</Panel></>; }