"use client";
import { Dialog } from "radix-ui";
import { AlertCircle, ChevronLeft, ChevronRight, LoaderCircle, X, Inbox } from "lucide-react";
import { Button } from "./button";
import { cn, label } from "@/lib/utils";
import type { ReactNode } from "react";

export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "green" | "amber" | "red" | "blue" | "neutral" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function Status({ value }: { value: string }) { return <Badge tone={["VERIFIED", "COMPLETED", "SALARIED", "CERTIFIED"].includes(value) ? "green" : ["PENDING", "SCHEDULED", "SENT", "SELF_EMPLOYED", "APPRENTICESHIP"].includes(value) ? "amber" : ["DISPUTED", "UNEMPLOYED"].includes(value) ? "red" : "neutral"}>{label(value)}</Badge>; }
export function Loading() { return <div className="loading-state" role="status"><LoaderCircle className="spin" size={22} /><span>Loading outcome data...</span></div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="error-state" role="alert"><AlertCircle size={20} /><span>{message}</span>{retry && <Button variant="outline" size="sm" onClick={retry}>Retry</Button>}</div>; }
export function Empty({ title, detail }: { title: string; detail?: string }) { return <div className="empty-state"><Inbox size={30} /><h3>{title}</h3>{detail && <p>{detail}</p>}</div>; }
export function PageHeader({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description?: string; children?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div><div className="heading-actions">{children}</div></div>; }
export function Panel({ title, subtitle, action, children, className }: { title: string; subtitle?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={cn("panel", className)}><div className="panel-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>; }
export function Modal({ open, onOpenChange, title, description, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; children: ReactNode }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay" /><Dialog.Content className="modal-content"><div className="modal-header"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description></div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Close dialog"><X size={18} /></Button></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function Pagination({ page, total, pageSize, onChange }: { page: number; total: number; pageSize: number; onChange: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="pagination"><span>{total ? `${(page - 1) * pageSize + 1}-${Math.min(page * pageSize, total)} of ${total}` : "0 records"}</span><div><Button variant="outline" size="icon" disabled={page <= 1} onClick={() => onChange(page - 1)} aria-label="Previous page"><ChevronLeft size={16} /></Button><span>{page} / {pages}</span><Button variant="outline" size="icon" disabled={page >= pages} onClick={() => onChange(page + 1)} aria-label="Next page"><ChevronRight size={16} /></Button></div></div>; }